<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.MCmoderSD</groupId>
    <artifactId>OpenAI</artifactId>
    <version>3.3.13</version>

    <name>OpenAI</name>
    <description>A Java Wrapper for the official OpenAI Java SDK</description>
    <url>https://github.com/MCmoderSD/OpenAI-Wrapper</url>

    <licenses>
        <license>
            <name>BSD 3-Clause License</name>
            <url>https://github.com/MCmoderSD/OpenAI-Wrapper/blob/master/LICENSE</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <url>https://github.com/MCmoderSD/OpenAI-Wrapper</url>
        <connection>scm:git:https://github.com/MCmoderSD/OpenAI-Wrapper.git</connection>
        <developerConnection>scm:git:https://github.com/MCmoderSD/OpenAI-Wrapper.git</developerConnection>
    </scm>

    <distributionManagement>
        <repository>
            <id>Nexus</id>
            <name>Sonatype Nexus</name>
            <url>https://mcmodersd.de/nexus/repository/maven-releases/</url>
        </repository>
    </distributionManagement>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <repositories>
        <repository>
            <id>Nexus</id>
            <name>Sonatype Nexus</name>
            <url>https://mcmodersd.de/nexus/repository/maven-releases/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.openai</groupId>
            <artifactId>openai-java</artifactId>
            <version>4.51.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.4.0</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>