package de.MCmoderSD.openai.objects;

import com.openai.models.chat.completions.ChatCompletion;
import com.openai.models.chat.completions.ChatCompletionMessage;
import com.openai.models.completions.CompletionUsage;

import java.sql.Timestamp;
import java.util.ArrayList;

/**
 * Represents a chat prompt containing user input, AI-generated output, metadata, and token usage statistics.
 */
@SuppressWarnings("unused")
public class ChatPrompt {

    // Parameters
    private final String input;
    private final ChatCompletion output;

    // Data
    private final String id;
    private final Timestamp timestamp;
    private final String model;
    private final String systemFingerprint;
    private final CompletionUsage usage;

    // Usage
    private final long promptTokens;
    private final long completionTokens;
    private final long totalTokens;

    // Content
    private final ArrayList<ChatCompletion.Choice> choices;
    private final ArrayList<ChatCompletionMessage> messages;
    private final ArrayList<String> content = new ArrayList<>();

    /**
     * Constructs a ChatPrompt instance with the provided user input and AI-generated response.
     *
     * @param input  The user's input prompt.
     * @param output The AI-generated response associated with the input.
     */
    @SuppressWarnings("OptionalGetWithoutIsPresent")
    public ChatPrompt(String input, ChatCompletion output) {

        // Initialize Parameters
        this.input = input;
        this.output = output;

        // Extract Data
        id = output.id();
        timestamp = new Timestamp(output.created() * 1000L);
        model = output.model();
        systemFingerprint = output.systemFingerprint().get();
        usage = output.usage().get();

        // Extract Usage
        promptTokens = usage.promptTokens();
        completionTokens = usage.completionTokens();
        totalTokens = usage.totalTokens();

        // Extract Content
        choices = new ArrayList<>(output.choices());
        messages = new ArrayList<>();
        choices.forEach(choice -> messages.add(choice.message()));
        messages.forEach(message -> {
            StringBuilder content = new StringBuilder();
            message.content().ifPresent(content::append);
            if (!content.isEmpty()) this.content.add(content.toString());
        });
    }

    /**
     * Returns the user input.
     *
     * @return The input string.
     */
    public String getInput() {
        return input;
    }

    /**
     * Returns the AI-generated output.
     *
     * @return The ChatCompletion output.
     */
    public ChatCompletion getOutput() {
        return output;
    }

    /**
     * Returns the unique identifier of the chat session.
     *
     * @return The chat session ID.
     */
    public String getId() {
        return id;
    }

    /**
     * Returns the timestamp of when the chat completion was created.
     *
     * @return The timestamp of the completion.
     */
    public Timestamp getTimestamp() {
        return timestamp;
    }

    /**
     * Returns the model used for generating the response.
     *
     * @return The model name.
     */
    public String getModel() {
        return model;
    }

    /**
     * Returns the system fingerprint associated with the AI response.
     *
     * @return The system fingerprint.
     */
    public String getSystemFingerprint() {
        return systemFingerprint;
    }

    /**
     * Returns the token usage statistics.
     *
     * @return The CompletionUsage object.
     */
    public CompletionUsage getUsage() {
        return usage;
    }

    /**
     * Returns the number of tokens used in the prompt.
     *
     * @return The prompt token count.
     */
    public long getPromptTokens() {
        return promptTokens;
    }

    /**
     * Returns the number of tokens used in the completion.
     *
     * @return The completion token count.
     */
    public long getCompletionTokens() {
        return completionTokens;
    }

    /**
     * Returns the total number of tokens used.
     *
     * @return The total token count.
     */
    public long getTotalTokens() {
        return totalTokens;
    }

    /**
     * Returns the first choice from the list of AI-generated choices.
     *
     * @return The first ChatCompletion.Choice object.
     */
    public ChatCompletion.Choice getChoice() {
        return choices.getFirst();
    }

    /**
     * Returns a specific choice by index from the list of AI-generated choices.
     *
     * @param index The index of the choice.
     * @return The ChatCompletion.Choice at the specified index.
     */
    public ChatCompletion.Choice getChoice(int index) {
        return choices.get(index);
    }

    /**
     * Returns all choices generated by the AI.
     *
     * @return A list of ChatCompletion.Choice objects.
     */
    public ArrayList<ChatCompletion.Choice> getChoices() {
        return choices;
    }

    /**
     * Returns the first message from the AI response.
     *
     * @return The first ChatCompletionMessage.
     */
    public ChatCompletionMessage getMessage() {
        return choices.getFirst().message();
    }

    /**
     * Returns a specific message by index from the AI response.
     *
     * @param index The index of the message.
     * @return The ChatCompletionMessage at the specified index.
     */
    public ChatCompletionMessage getMessage(int index) {
        return choices.get(index).message();
    }

    /**
     * Returns all messages from the AI response.
     *
     * @return A list of ChatCompletionMessage objects.
     */
    public ArrayList<ChatCompletionMessage> getMessages() {
        return messages;
    }

    /**
     * Returns all textual content extracted from the AI response.
     *
     * @return A list of strings representing the response content.
     */
    public ArrayList<String> getContent() {
        return content;
    }
}